name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/learner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist